title: Dfpello | Security Writeups
description: Offensive Security & CTF Solutions
theme: jekyll-theme-hacker 

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  convertToHtml: true